routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' =>['web']],function (){

    //login and register
Route::post('login',['uses'=>'Auth\LoginController@login','as'=>'login']);
Route::get('logout',['uses'=>'Auth\LoginController@logout','as'=>'logout']);
Route::post('register',['uses'=>'Auth\RegisterController@register','as'=>'register']);

//send reset password to email
Route::post('password.email','Auth\ForgotPasswordController@sendResetLinkEmail');
Route::post('password.reset','Auth\ResetPasswordController@reset');
Route::get('password.reset','Auth\ForgotPasswordController@showLinkRequestForm');
Route::get('password.reset.{token}','Auth\ResetPasswordController@showResetForm');

//categories
Route::resource('categories','CategoryController',['except'=>'create']);
//tags
Route::resource('tags','TagController',['except'=>'create']);

//comments
Route::post('comments/{id}',['uses'=>'CommentsController@store','as'=>'comments.store']);
Route::get('comments/{id}/edit',['uses'=>'CommentsController@edit','as'=>'comments.edit']);
Route::put('comments/{id}',['uses'=>'CommentsController@update','as'=>'comments.update']);
Route::delete('comments/{id}',['uses'=>'CommentsController@destroy','as'=>'comments.destroy']);
Route::get('comments/{id}/delete',['uses'=>'CommentsController@delete','as'=>'comments.delete']);

Route::get('blog/{slug}',['as'=>'blog.single','uses'=>'BlogController@getSingle'])->where('slug','[\w\d\-\_]+');
Route::get('blogs',['uses'=>'BlogController@getIndex', 'as'=>'blogs.index']);

Route::get('/','PagesController@getHome');
Route::get('/about','PagesController@getAbout');
Route::get('/blog','PagesController@getBlog');
Route::resource('posts','PostController');
Route::get('/contact',['uses'=>'PagesController@getContact','as'=>'contact']);
Route::post('contact','PagesController@postContact');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('contact/submit','MessagesController@submit');
Route::get('messages',['uses'=>'MessagesController@getMessages','as'=>'messages']);
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
    public function posts(){
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Session;
class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tags = Tag::all();
        return view('tags.index')->withTags($tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,['name'=>'required']);
        $tag=new Tag;
        $tag->name=$request->name;
        $tag->save();

        Session::flash('success','New tag was successfully created');
        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $tag = Tag::find($id);
        return view('tags.show')->withTag($tag);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $tag=Tag::find($id);
        return view('tags.edit')->withTag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $tag=Tag::find($id);
        $this->validate($request,['name'=>'required']);
        $tag->name=$request->name;
        $tag->save();

        Session::flash('success','Successfully saved new tag.');
        return redirect()->route('tags.show',$tag->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $tag=Tag::find($id);
        $tag->posts()->detach();

        $tag->delete();
        Session::flash('success','Tag was deleted successfully');

        return redirect()->route('tags.index');
    }
}

resources/views/tags/edit.blade.php
@extends('layouts.app')
@section('title','| Edit tag')
@section('content')
    {{Form::model($tag,['route'=>['tags.update',$tag->id],'method'=>'PUT'])}}
    {{Form::label('name','Title: ')}}
    {{Form::text('name',null,['class'=>'form-control'])}}
    {{Form::submit('Save changes',['class'=>'btn btn-success','style'=>'margin-top:20px;'])}}
    {{Form::close()}}
    @endsection

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('title','| All Tags')
@section('content')
    <h1>Tags</h1>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>

        </tr>
        </thead>
        <tbody>
        @foreach($tags as $tag)
            <tr>
                <th>{{$tag->id}}</th>
                <td><a href="{{route('tags.show',$tag->id)}}">{{$tag->name}} </a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection
@section('sidebar')
    {{Form::open(['route'=>'tags.store','methos'=>'POST'])}}

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">New Tag:</h5>
            <p class="card-text">Create</p>
            <hr>
            <dl class="list-group-item">
                <dt> {{Form::label('name','Name: ')}}</dt>
                <dd>{{Form::text('name',null,['class'=>'form-control'])}}</dd>
                {{Form::submit('Create new tag',['class'=>'btn btn-primary btn-block'])}}
            </dl>
            <hr>



        </div>
    </div>

    {{Form::close()}}
@endsection
@section('body')
    <hr>
@endsection

resources/views/tags/show.blade.php
@extends('layouts.app')
@section('title', "$tag->name Tag")
@section('content')
    <h1> {{$tag->name }} Tag <small>{{$tag->posts()->count()}} Posts</small></h1>
    <div class="row">
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Tags</th>
            <th>View</th>
        </tr>
        </thead>
        <tbody>
        @foreach($tag->posts as $post)
        <tr>
        <th>{{$post->id}}</th>
            <td>{{$post->title}}</td>
            <td>@foreach($post->tags as $tag)

                <span class="btn btn-secondary btn-sm">{{$tag->name}}</span>
                @endforeach
            </td>
            <td><a href="{{route('posts.show',$post->id)}}" class="btn btn-success btn-sm">View</a></td>
        </tr>
            @endforeach
        </tbody>
    </table>
    </div>
    @endsection
@section('sidebar')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Tags:</h5>
            <p class="card-text">Editing</p>
            <dl class="list-group-item">
                <dt>Tags:</dt>
                <dd><a href="{{route('tags.edit',$tag->id)}}" class="btn btn-primary btn-block">Edit</a></dd>
                <hr>
                <dd>{{Form::open(['route'=>['tags.destroy',$tag->id],'method'=>'DELETE'])}}
                    {{Form::submit('Delete',['class'=>'btn btn-danger btn-block'])}}
                    {{Form::close()}}
                </dd>
            </dl>



        </div>
    </div>
@endsection