routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' =>['web']],function (){

    //login and register
Route::post('login',['uses'=>'Auth\LoginController@login','as'=>'login']);
Route::get('logout',['uses'=>'Auth\LoginController@logout','as'=>'logout']);
Route::post('register',['uses'=>'Auth\RegisterController@register','as'=>'register']);

//send reset password to email
Route::post('password.email','Auth\ForgotPasswordController@sendResetLinkEmail');
Route::post('password.reset','Auth\ResetPasswordController@reset');
Route::get('password.reset','Auth\ForgotPasswordController@showLinkRequestForm');
Route::get('password.reset.{token}','Auth\ResetPasswordController@showResetForm');

//categories
Route::resource('categories','CategoryController',['except'=>'create']);
//tags
Route::resource('tags','TagController',['except'=>'create']);

//comments
Route::post('comments/{id}',['uses'=>'CommentsController@store','as'=>'comments.store']);
Route::get('comments/{id}/edit',['uses'=>'CommentsController@edit','as'=>'comments.edit']);
Route::put('comments/{id}',['uses'=>'CommentsController@update','as'=>'comments.update']);
Route::delete('comments/{id}',['uses'=>'CommentsController@destroy','as'=>'comments.destroy']);
Route::get('comments/{id}/delete',['uses'=>'CommentsController@delete','as'=>'comments.delete']);

Route::get('blog/{slug}',['as'=>'blog.single','uses'=>'BlogController@getSingle'])->where('slug','[\w\d\-\_]+');
Route::get('blogs',['uses'=>'BlogController@getIndex', 'as'=>'blogs.index']);

Route::get('/','PagesController@getHome');
Route::get('/about','PagesController@getAbout');
Route::get('/blog','PagesController@getBlog');
Route::resource('posts','PostController');
Route::get('/contact',['uses'=>'PagesController@getContact','as'=>'contact']);
Route::post('contact','PagesController@postContact');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('contact/submit','MessagesController@submit');
Route::get('messages',['uses'=>'MessagesController@getMessages','as'=>'messages']);
});

resources/views/includes/body.blade.php
<div class="container">
    @if(Request::is('/'))
        @include('includes.showcase')
    @endif
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-lg-8">
                @include('includes.messages')
                @yield('content')
            </div>
            <div class="col-xs-12 col-sm-4 col-lg-4">
                @include('includes.sidebar')
            </div>
        </div>
    </div>
</div>
<div class="container text-center">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            @yield('body')
        </div>
    </div>
</div>

resources/views/includes/footer.blade.php
<footer id="footer" class="text-center">
    <p>Copyright 2018 &copy; BLW </p>
</footer>

resources/views/includes/head.blade.php
@yield('stylesheet')

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" type="text/css" href="/css/parsley.css">
<link rel="stylesheet" type="text/css" href="/css/app.css">
<link rel="stylesheet" type="text/css" href="/css/styles.css">
<link rel="stylesheet"  type="text/css" href="/css/select2.min.css">
<link href="/open-iconic/font/css/open-iconic-bootstrap.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{{Html::style('css/styles.css') }}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
<title>Basic Laravel Website @yield('title')</title>

resources/views/includes/messages.blade.php
@if(Session::has('success'))
    <div class="alert alert-success" role="alert">
        <strong>Success:</strong> {{Session::get('success')}}
    </div>
@endif

@if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        <strong>Errors:</strong>
        <ul>
            @foreach($errors->all() as $error)

                <li>{{$error}}</li>

            @endforeach
        </ul>
    </div>
@endif

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-light">
    <a class="navbar-brand" href="/">Basic Laravel Website</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="{{Request::is('/') ? 'active' : ''}}">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {{Request::is('about') ? 'active' : ''}}">
                <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item {{Request::is('blog') ? 'active' : ''}}">
                <a class="nav-link" href="/blog">Blog</a>
            </li>
            <li class="nav-item {{Request::is('contact') ? 'active' : ''}}">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if(Auth::check())

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Hello: {{Auth::user()->name}}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{route('posts.index')}}">Posts</a>
                    <a class="dropdown-item" href="{{route('messages')}}">Messages</a>
                    <a class="dropdown-item" href="{{route('categories.index')}}">Categories</a>
                    <a class="dropdown-item" href="{{route('tags.index')}}">Tags</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{route('logout')}}">Logout</a>
                </div>
            </li>
                @else

                 <li>   <a href="{{route('login')}}" class="btn btn-outline-success my-2 my-sm-0">Login</a></li>

                <li><a href="{{route('register')}}" class="btn btn-outline-danger my-2 my-sm-0">Register</a></li>

                @endif
        </ul>

    </div>
</nav>

resources/views/includes/scripts.blade.php
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@yield('scripts')
<script type="text/javascript" src="/js/parsley.min.js"></script>
<script type="text/javascript" src="/js/select2.min.js"></script>

resources/views/includes/showcase.blade.php
<div class="jumbotron text-center animated bounceInUp">
    <h1 class="display-4">Basic Laravel Website!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
        <a class="btn btn-success" href="#" role="button">Learn more</a>
    </p>
</div>

resources/views/includes/sidebar.blade.php
@section('sidebar')
    <div class="card card-body bg-light">
        <h3>Sidebar</h3>
        This is the sidebar
    </div>
@show